version: '3'

services:
  app:
    build: 
      context: .
      args:
        - IMAGE_VERSION=3.7.0-alpine3.8
    image: takacsmark/flask-redis:1.0
    env_file: .env.txt
    ports:
      - 80:5000
      - 80:5000
    dns: 888.888.8888
    networks:
      - mynet
  app2:
    image: ubuntu:latest
    command: ["tail", "-f", "/dev/null"]
  redis:
    imge: redis:4.0.11-alpine
    networks:
      - mynet
    volume:
      - mydata:/data

network:
  mynet:
volumes:
  mydata:
